/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-22 20:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.challengeCrtfd;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class challengeCrtfdList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>챌린지 인증 메인 페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/challengeCr/ch_cr_list.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 해더 영역 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"ch\">\r\n");
      out.write("            <div id=\"ch-a\" class=\"ch-float\">\r\n");
      out.write("                <h1>챌린져스 인증 게시판</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"ch-s\" class=\"ch-float\">\r\n");
      out.write("                <ul>  \r\n");
      out.write("                    <li><a href=\"challengeCrtfdInsert.jsp\">챌린지 <strong>인증</strong>하러가기 -></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 카테고리 선택 -->\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <hr>  <!-- 차후 이미지로 교체 예정  -->\r\n");
      out.write("        <div class=\"cat-area\">\r\n");
      out.write("            <div class=\"cat\">\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">전체</a>\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">건강</a>\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">관계</a> \r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">생활</a> \r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">역량</a> \r\n");
      out.write("            </div> \r\n");
      out.write("            <div class=\"cat-2\">\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">자산</a> \r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">취미</a>\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">공부</a>\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">돈 관리</a>\r\n");
      out.write("                <a id=\"cat-mg\" class=\"cat-float\" href=\"#\">그 외</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 정렬 -->\r\n");
      out.write("\t\t<div class=\"sort\">\r\n");
      out.write("\t\t\t<form action=\"#\" >\r\n");
      out.write("\t\t\t\t<select name=\"sk\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t<option value=\"new\">최신순</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"like\">조회순</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 인증 글 목록 --> <!-- 번갈아가면서 색깔주는거 나중에 추가하기 -->\r\n");
      out.write("\t\t<div class=\"list-wrapper\">\r\n");
      out.write("\t\t\t<table class=\"table\" id=\"list-table\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 조회된 목록이 없을 때   -->\r\n");
      out.write("\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\">존재하는 인증글이 없습니다</td>\r\n");
      out.write("\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t<tr>   \r\n");
      out.write("\t\t\t\t\t\t<td>112</td>\r\n");
      out.write("\t\t\t\t\t\t<td>제목 출력</td>\r\n");
      out.write("\t\t\t\t\t\t<td>작성자 출력</td>\r\n");
      out.write("\t\t\t\t\t\t<td>5</td>\r\n");
      out.write("\t\t\t\t\t\t<td>날짜 출력</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <!-- 페이지 번호 목록 -->\r\n");
      out.write("        <div class=\"page-no-area\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">&lt;&lt;</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">&lt;</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">1</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">&gt;</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">&gt;&gt;</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 검색 -->\r\n");
      out.write("        <div class=\"search\">\r\n");
      out.write("        \t<form class=\"search-form\">\r\n");
      out.write("        \t\t<select name=\"sk\" class=\"s-form-control1\">\r\n");
      out.write("        \t\t\t<option>제목</option>\r\n");
      out.write("        \t\t\t<option>작성자</option>\r\n");
      out.write("        \t\t\t<option>내용</option>\r\n");
      out.write("        \t\t\t<option>내용+제목</option>\r\n");
      out.write("        \t\t</select>\r\n");
      out.write("        \t\t<input type=\"text\" name=\"sv\" class=\"s-form-control2\">\r\n");
      out.write("        \t\t<button class=\"s-form-control3\">검색</button> \r\n");
      out.write("        \t</form>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 푸터 영역 -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
