/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-23 01:39:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.center;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class centerMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\th1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\ttext-shadow: 1px 1px 2px black;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#centerArea {\r\n");
      out.write("\t\tmargin-bottom: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#searchWrapper {\r\n");
      out.write("\t\tmin-height: 400px;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#selectArea {\r\n");
      out.write("\t\tborder-image: linear-gradient(to right, rgb(146, 161, 230) 90%, lightgray 100%);\r\n");
      out.write("\t\tborder-image-slice: 1;\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-image-width: 5px;\r\n");
      out.write("\t\tbackground: #f7f7f7;\r\n");
      out.write("\t\twidth: 10%;\t\r\n");
      out.write("\t\tpadding: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    #sidoSelect {\r\n");
      out.write("    \tmargin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\t#gugunSelectArea {\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\twidth: 80%;\r\n");
      out.write("\t\theight: 70px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#centerSelectArea {\r\n");
      out.write("\t\toverflow-x: hidden;\r\n");
      out.write("\t\toverflow-y: scroll;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 800px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t#listMap {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#centerListArea {\r\n");
      out.write("\t\tborder-image: linear-gradient(to right, lightgray 0%,  rgb(146, 161, 230)100%);\r\n");
      out.write("\t\tborder-image-slice: 1;\r\n");
      out.write("\t\tborder-style: solid;\r\n");
      out.write("\t\tborder-image-width: 5px;\r\n");
      out.write("\t\tbackground: #f7f7f7;\r\n");
      out.write("\t\twidth: 25%;\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#mapArea {\r\n");
      out.write("\t\twidth: 65%;\r\n");
      out.write("\t\theight: 800px;\r\n");
      out.write("\t}\r\n");
      out.write("  \r\n");
      out.write("\tlabel {\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#centerList {\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#centerList > li {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tborder-bottom: 2px solid lightgray;\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/btnStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <h1>기관찾기</h1>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t<!-- 기관 검색 -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"listMap\">\r\n");
      out.write("\t\t\t<!-- 기관 목록 -->\r\n");
      out.write("\t\t\t<div id =\"selectArea\">\r\n");
      out.write("\t\t\t\t시/도 : <select name=\"sidoSelect\" id=\"sidoSelect\"></select>\r\n");
      out.write("\t\t\t\t<button id=\"search-btn\" class=\"btn-style1\">찾기</button> \r\n");
      out.write("\t\t\t\t\t<div id=\"gugunSelectArea\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>   \r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div id=\"centerListArea\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"centerSelectArea\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"centerList\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>  \r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 지도 -->\r\n");
      out.write("\t\t\t<div id=\"mapArea\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\t\r\n");
      out.write("\t\tvar userAddress = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberAddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tvar sidoArea = [\"시/도 선택\",\"서울특별시\",\"인천광역시\",\"대전광역시\",\"광주광역시\",\"대구광역시\",\"울산광역시\",\"부산광역시\",\"경기도\",\"강원도\",\"충청북도\",\"충청남도\",\"전라북도\",\"전라남도\",\"경상북도\",\"경상남도\",\"제주도\"];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar gugun1 = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("\t\tvar gugun2 = [\"계양구\",\"남구\",\"남동구\",\"동구\",\"부평구\",\"서구\",\"연수구\",\"중구\",\"강화군\",\"옹진군\"];\r\n");
      out.write("\t\tvar gugun3 = [\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"];\r\n");
      out.write("\t\tvar gugun4 = [\"광산구\",\"남구\",\"동구\",\"북구\",\"서구\"];\r\n");
      out.write("\t\tvar gugun5 = [\"남구\",\"달서구\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\",\"달성군\"];\r\n");
      out.write("\t\tvar gugun6 = [\"남구\",\"동구\",\"북구\",\"중구\",\"울주군\"];\r\n");
      out.write("\t\tvar gugun7 = [\"강서구\",\"금정구\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\",\"기장군\"];\r\n");
      out.write("\t\tvar gugun8 = [\"고양시\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시\",\"수원시\",\"시흥시\",\"안산시\",\"안성시\",\"안양시\",\"양주시\",\"오산시\",\"용인시\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\",\"가평군\",\"양평군\",\"여주군\",\"연천군\"];\r\n");
      out.write("\t\tvar gugun9 = [\"강릉시\",\"동해시\",\"삼척시\",\"속초시\",\"원주시\",\"춘천시\",\"태백시\",\"고성군\",\"양구군\",\"양양군\",\"영월군\",\"인제군\",\"정선군\",\"철원군\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("\t\tvar gugun10 = [\"제천시\",\"청주시\",\"충주시\",\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"증평군\",\"진천군\",\"청원군\"];\r\n");
      out.write("\t\tvar gugun11 = [\"계룡시\",\"공주시\",\"논산시\",\"보령시\",\"서산시\",\"아산시\",\"천안시\",\"금산군\",\"당진군\",\"부여군\",\"서천군\",\"연기군\",\"예산군\",\"청양군\",\"태안군\",\"홍성군\"];\r\n");
      out.write("\t\tvar gugun12 = [\"군산시\",\"김제시\",\"남원시\",\"익산시\",\"전주시\",\"정읍시\",\"고창군\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"임실군\",\"장수군\",\"진안군\"];\r\n");
      out.write("\t\tvar gugun13 = [\"광양시\",\"나주시\",\"목포시\",\"순천시\",\"여수시\",\"강진군\",\"고흥군\",\"곡성군\",\"구례군\",\"담양군\",\"무안군\",\"보성군\",\"신안군\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"];\r\n");
      out.write("\t\tvar gugun14 = [\"경산시\",\"경주시\",\"구미시\",\"김천시\",\"문경시\",\"상주시\",\"안동시\",\"영주시\",\"영천시\",\"포항시\",\"고령군\",\"군위군\",\"봉화군\",\"성주군\",\"영덕군\",\"영양군\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\"];\r\n");
      out.write("\t\tvar gugun15 = [\"거제시\",\"김해시\",\"마산시\",\"밀양시\",\"사천시\",\"양산시\",\"진주시\",\"진해시\",\"창원시\",\"통영시\",\"거창군\",\"고성군\",\"남해군\",\"산청군\",\"의령군\",\"창녕군\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"];\r\n");
      out.write("\t\tvar gugun16 = [\"서귀포시\",\"제주시\",\"남제주군\",\"북제주군\"];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar address = \"\"; // 주소 담을 변수\r\n");
      out.write("\t\tvar centerNameAry = new Array(); // 센터 명 배열에 담기\r\n");
      out.write("\t\tvar centerName = \"\"; // 센터명 담을 변수\r\n");
      out.write("\t\tvar flagNum = 0; //\r\n");
      out.write("\t\tvar flagNum2 = 0; //\r\n");
      out.write("\t\tvar positionX = new Array(); // x좌표 담기\r\n");
      out.write("\t\tvar positionY = new Array(); // y좌표 담기\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar searchOn = 0;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\tconsole.log(address);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 찾기 버튼 클릭 시\r\n");
      out.write("\t\t$(\"#search-btn\").on(\"click\", function() {\r\n");
      out.write("\t\t\tif($(':checkbox[name=\"gugunSelect\"]:checked').length < 1){\r\n");
      out.write("\t\t\t\talert('지역을 선택해주세요');                        \r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\tvar sido = $(\"#sidoSelect option:selected\").val();\r\n");
      out.write("\t\t\tvar gugun = new Array();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"input:checkbox[name='gugunSelect']:checked\").each(function(){\r\n");
      out.write("\t\t\t\tgugun.push($(this).val());\r\n");
      out.write("\t\t\t}) \t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t$.ajaxSettings.traditional = true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/center/selectCenterList.do\", \r\n");
      out.write("\t\t\t\tdata : {\"sido\" : sido, \r\n");
      out.write("\t\t\t\t\t\t\t\t\"gugun\" : gugun}, \r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdataType : \"JSON\",\r\n");
      out.write("\t\t\t\tsuccess : function(cList) {\r\n");
      out.write("\t\t\t\t\t$(\"#centerList\").html(\"\");\r\n");
      out.write("\t\t\t\t\taddress = \"\";\r\n");
      out.write("\t\t\t\t\taddressAry = new Array();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.each(cList, function(index, item){\r\n");
      out.write("\t\t\t\t\t\tvar li = $(\"<li>\").addClass(\"center-row\");\r\n");
      out.write("\t\t\t\t\t\tvar placeSearchBtn = $(\"<button>\").text(\"위치찾기\").addClass(\"placeSearchBtn btn-style1\").attr(\"onclick\", \"placeSearch(this)\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar div = $(\"<div>\");\r\n");
      out.write("\t\t\t\t\t\tvar br = $(\"<br>\");\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar centerTitle = $(\"<h2>\").addClass(\"centerName\").text(item.centerName);\r\n");
      out.write("\t\t\t\t\t\tvar centerCla = $(\"<p>\").addClass(\"centerCla\").text(item.centerCla);\r\n");
      out.write("\t\t\t\t\t\tvar centerName = $(\"<p>\").addClass(\"centerName\").text(item.centerName);\r\n");
      out.write("\t\t\t\t\t\tvar centerPhone = $(\"<p>\").addClass(\"centerPhone\").text(item.centerTel);\r\n");
      out.write("\t\t\t\t\t\tvar centerUrl = $(\"<a>\").addClass(\"centerUrl\").attr(\"href\", \"http://\"+item.centerUrl).text(item.centerUrl);\r\n");
      out.write("\t\t\t\t\t\tvar centerAddr = $(\"<p>\").addClass(\"centerAddr\").text(item.centerAddr);\r\n");
      out.write("\t\t\t\t\t\tvar centerAddr2 = $(\"<p>\").addClass(\"centerAddr2\").text(item.centerAddrDtl);\r\n");
      out.write("\t\t\t\t\t\t// \r\n");
      out.write("\t\t\t\t\t\tconsole.log(item.centerUrl);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdiv.append(centerTitle).append(centerCla).append(centerPhone).append(centerUrl).append(centerAddr).append(centerAddr2).append(placeSearchBtn);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tli.append(div);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#centerList\").append(li);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\taddress = item.centerAddr;\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tcenterName = item.centerName;\r\n");
      out.write("\t\t\t\t\t\tsearchAddress(centerName);\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tflagNum = flagNum + 1;\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write(" \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}, error : function(request, status, error) {\r\n");
      out.write("\t\t\t  \t   alert(\"code = \"+ request.status + \" message = \" + request.responseText + \" error = \" + error); // 실패 시 처리\r\n");
      out.write("\t\t\t \t}\t\r\n");
      out.write("\t\t\t}); \t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 위치찾기 버튼 클릭 시\r\n");
      out.write("\t\tfunction placeSearch(ele){\r\n");
      out.write("\t\t\t\tvar thisAddr = $(ele).prev().prev().text()\r\n");
      out.write("\t\t\t\tcenterName = $(ele).prev().prev().prev().prev().prev().prev().prev().text();\r\n");
      out.write("\t\t\t\tplaceSearchMarker(thisAddr);\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 구/군 선택 시 위도 경도 배열에 담기\r\n");
      out.write("\t\tfunction searchAddress(centerName) {\r\n");
      out.write("\t\t\tcenterNameAry = new Array();\r\n");
      out.write("\t\t\tsearchOn = 0;\r\n");
      out.write("\t\t\tpositionX = new Array(); // x좌표 담기\r\n");
      out.write("\t\t\tpositionY = new Array(); // y좌표 담기\r\n");
      out.write("\t\t\t// =================================== 위도 경도 =====================================\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("         url:'https://dapi.kakao.com/v2/local/search/address.json?query='+encodeURIComponent(address),\r\n");
      out.write("         type:'GET',\r\n");
      out.write("         headers: {'Authorization' : 'KakaoAK 95bd3f68d02962b41f5efde3edf2ad26'},\r\n");
      out.write("\t\t\t   success:function(data){\r\n");
      out.write("\t\t\t\t   \t try {\r\n");
      out.write("\t\t\t\t\t   \t flagNum2 = flagNum2 + 1;\r\n");
      out.write("\t\t\t\t\t       positionY.push(data['documents'][0]['y']); \r\n");
      out.write("\t\t\t\t  \t\t\t positionX.push(data['documents'][0]['x']);\r\n");
      out.write("\t\t\t\t\t\t   \t centerNameAry.push(centerName);\r\n");
      out.write("\t\t\t\t\t       if(flagNum2 == flagNum) {\r\n");
      out.write("\t\t\t\t\t    \t   pickMarkers();\r\n");
      out.write("\t\t\t\t\t       }\t\t\t   \t\t \r\n");
      out.write("\t\t\t\t   \t } catch(error) {\r\n");
      out.write("\t\t\t\t   \t\t \r\n");
      out.write("\t\t\t\t   \t }\r\n");
      out.write("\r\n");
      out.write("\t\t\t   },\t\t\t   \r\n");
      out.write("\t\t\t   error : function(e){\r\n");
      out.write("\t\t\t       console.log(e);\r\n");
      out.write("\t\t\t   },\t\t\t\t\t\t   \t\t\t\t\r\n");
      out.write("\t\t\t});\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 위치 찾기 시 위도 경도 담기\r\n");
      out.write("\t\tfunction placeSearchMarker(thisAddr) {\r\n");
      out.write("\t\t\tsearchOn = 0;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("         url:'https://dapi.kakao.com/v2/local/search/address.json?query='+encodeURIComponent(thisAddr),\r\n");
      out.write("         type:'GET',\r\n");
      out.write("         headers: {'Authorization' : 'KakaoAK 95bd3f68d02962b41f5efde3edf2ad26'},\r\n");
      out.write("\t\t\t   success:function(data){\r\n");
      out.write("\t\t\t\t   \t searchOn = 1;\r\n");
      out.write("\t\t\t\t   \t var x = data['documents'][0]['x'];\r\n");
      out.write("\t\t\t\t   \t var y = data['documents'][0]['y']; \r\n");
      out.write("\t\t\t\t   \t pickMarkers(x, y);\r\n");
      out.write("\t\t\t   },\t\t\t   \r\n");
      out.write("\t\t\t   error : function(e){\r\n");
      out.write("\t\t\t       console.log(e);\r\n");
      out.write("\t\t\t   },\t\t\t\t\t\t   \t\t\t\t\r\n");
      out.write("\t\t\t});\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t}      \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// =================================== 지도 =====================================\t\r\n");
      out.write("\t\tfunction pickMarkers(x, y) {\r\n");
      out.write("\t\t\tvar container = document.getElementById('mapArea'); //지도를 담을 영역의 DOM 레퍼런스\r\n");
      out.write("\t\t\tvar options = { //지도를 생성할 때 필요한 기본 옵션  \r\n");
      out.write("\t\t\t\tcenter: new kakao.maps.LatLng(positionY[0], positionX[0]), //지도의 중심좌표.\r\n");
      out.write("\t\t\t\tlevel: 3 //지도의 레벨(확대, 축소 정도)\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t\tvar points = [];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i < positionY.length; ++i) {\r\n");
      out.write("\t\t\t\tpoints[i] = new kakao.maps.LatLng(positionY[i], positionX[i]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 지도를 재설정할 범위정보를 가지고 있을 LatLngBounds 객체를 생성합니다\r\n");
      out.write("\t\t\tvar bounds = new kakao.maps.LatLngBounds();    \r\n");
      out.write("\r\n");
      out.write("\t\t\tvar i, marker;\r\n");
      out.write("\t\t\tfor (i = 0; i < points.length; i++) {\r\n");
      out.write("\t\t\t    // 배열의 좌표들이 잘 보이게 마커를 지도에 추가합니다\r\n");
      out.write("\t\t\t    marker =     new kakao.maps.Marker({ position : points[i] });\r\n");
      out.write("\t\t\t    marker.setMap(map);\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    // 마커마다 윈도우 표시하기 //////////////////////////\r\n");
      out.write("\t\t\t    var iwContent = '<div style=\"padding:5px;\">' + centerNameAry[i] + '</div>',\r\n");
      out.write("\t\t\t    iwPosition = new kakao.maps.LatLng(positionY[i], positionX[i]);\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t    var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("\t\t\t        position : iwPosition, \r\n");
      out.write("\t\t\t        content : iwContent \r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t      \r\n");
      out.write("\t\t\t    // 마커 위에 인포윈도우를 표시합니다. 두번째 파라미터인 marker를 넣어주지 않으면 지도 위에 표시됩니다\r\n");
      out.write("\t\t\t    infowindow.open(map, marker); \r\n");
      out.write("\t\t\t    ////////////////////////////////////////////\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    // LatLngBounds 객체에 좌표를 추가합니다\r\n");
      out.write("\t\t\t    bounds.extend(points[i]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction setBounds() {\r\n");
      out.write("\t\t\t    // LatLngBounds 객체에 추가된 좌표들을 기준으로 지도의 범위를 재설정합니다\r\n");
      out.write("\t\t\t    // 이때 지도의 중심좌표와 레벨이 변경될 수 있습니다\r\n");
      out.write("\t\t\t    map.setBounds(bounds);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 만약 위치 찾기 버튼 클릭하면\r\n");
      out.write("\t\t\t\tif(searchOn == 1) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar moveLatLon = new kakao.maps.LatLng(y, x);\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t    // 지도 중심을 부드럽게 이동시킵니다\r\n");
      out.write("\t\t\t    // 만약 이동할 거리가 지도 화면보다 크면 부드러운 효과 없이 이동합니다\r\n");
      out.write("\t\t\t\t  map.panTo(moveLatLon);  \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t// 초기 select 설정\r\n");
      out.write("\t$(function(){  \t  \r\n");
      out.write("\t\t$(\"#sidoSelect\").each(function() {\r\n");
      out.write("\t\t\t\tfor(var i = 0; i < sidoArea.length; ++i) {\r\n");
      out.write("\t\t\t\t\t$(this).append(\"<option value='\"+sidoArea[i]+\"'>\"+sidoArea[i]+\"</option>\");\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t});\t  \t \r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 시 도 체크시\r\n");
      out.write("\t\t$(\"#sidoSelect\").on(\"change\", function(){\r\n");
      out.write("//\t\t\tconsole.log($(\"#sidoSelect option:selected\").val());\r\n");
      out.write("\t\t\t$(\"#gugunSelectArea\").empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar sidoIndex = $(\"#sidoSelect option\").index($(\"#sidoSelect option:selected\"));\r\n");
      out.write("\t\t\t\r\n");
      out.write("//\t\t\tconsole.log(sidoIndex);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 서울\r\n");
      out.write("\t\t\tif(sidoIndex == 1) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun1.length; ++j) {  \t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun1[j] + \">\" + gugun1[j] +\"</label>\");\t \r\n");
      out.write("\t\t\t\t\t// if(j > 1 && j % 10 == 0) {\r\n");
      out.write("\t\t\t\t\t// \t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t\t// }\t  \t\t\t\r\n");
      out.write("\t\t\t\t}  \r\n");
      out.write("\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 인천\r\n");
      out.write("\t\t\tif(sidoIndex == 2) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun2.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t  */ \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun2[j] + \">\" + gugun2[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 대전\r\n");
      out.write("\t\t\tif(sidoIndex == 3) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun3.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun3[j] + \">\" + gugun3[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 광주\r\n");
      out.write("\t\t\tif(sidoIndex == 4) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun4.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun4[j] + \">\" + gugun4[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 대구\r\n");
      out.write("\t\t\tif(sidoIndex == 5) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun5.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t  */ \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun5[j] + \">\" + gugun5[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 울산\r\n");
      out.write("\t\t\tif(sidoIndex == 6) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun6.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t  */ \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun6[j] + \">\" + gugun6[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 부산\r\n");
      out.write("\t\t\tif(sidoIndex == 7) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun7.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun7[j] + \">\" + gugun7[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 경기도\r\n");
      out.write("\t\t\tif(sidoIndex == 8) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun8.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t  */ \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun8[j] + \">\" + gugun8[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 강원도\r\n");
      out.write("\t\t\tif(sidoIndex == 9) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun9.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun9[j] + \">\" + gugun9[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 충청북도\r\n");
      out.write("\t\t\tif(sidoIndex == 10) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun10.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun10[j] + \">\" + gugun10[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 충청남도\r\n");
      out.write("\t\t\tif(sidoIndex == 11) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun11.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t  */ \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun11[j] + \">\" + gugun11[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 전라북도\r\n");
      out.write("\t\t\tif(sidoIndex == 12) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun12.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun12[j] + \">\" + gugun12[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 전라남도\r\n");
      out.write("\t\t\tif(sidoIndex == 13) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun13.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun13[j] + \">\" + gugun13[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 경상북도\r\n");
      out.write("\t\t\tif(sidoIndex == 14) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun14.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun14[j] + \">\" + gugun14[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 경상남도\r\n");
      out.write("\t\t\tif(sidoIndex == 15) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun15.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t} */\t  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun15[j] + \">\" + gugun15[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 제주도\r\n");
      out.write("\t\t\tif(sidoIndex == 16) {\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < gugun16.length; ++j) {\r\n");
      out.write("\t/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t\t\t\t}\t */  \t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun16[j] + \">\" + gugun16[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t}    \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t});\r\n");
      out.write("    \r\n");
      out.write("    // 시 도 체크시 \r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=78d99faa53b972374c1a1fb343c1f1a3&libraries=services\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
