/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 21:51:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminBlacklistInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>블랙리스트 조회 페이지</title>\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JS -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    <style>\r\n");
      out.write("\t.admin_content{ \r\n");
      out.write("\t    width: 70%;\r\n");
      out.write("\t    height: 100%;\r\n");
      out.write("\t    margin: auto;\r\n");
      out.write("\t\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t    text-overflow: ellipsis;\r\n");
      out.write("\t    white-space: nowrap;\r\n");
      out.write("\t\r\n");
      out.write("\t }\r\n");
      out.write("\t\r\n");
      out.write("\t.admin_black_title{\r\n");
      out.write("\t    margin: 3% 0 3% 0;\r\n");
      out.write("\t    color:rgb(40, 62, 105);\r\n");
      out.write("\t    \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.admin_black_board{ \r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.page_area{ margin-top: 2%; }\r\n");
      out.write("\t\r\n");
      out.write("\t.black_search{ text-align: center; }\r\n");
      out.write("\t\r\n");
      out.write("\t.page-item > a, .page-item > a:hover{ color: black; }\r\n");
      out.write("\t\r\n");
      out.write("\t#black_btn { \r\n");
      out.write("\t    background-color: #343a40;\r\n");
      out.write("\t    color: snow;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#black_btn2 { \r\n");
      out.write("\t    background-color: #dc3545;\r\n");
      out.write("\t    color: snow;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("    \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/adminMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"admin_content\">\r\n");
      out.write("            <div class=\"admin_black_title\">\r\n");
      out.write("                <h4>블랙리스트 조회</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"admin_black_board\">\r\n");
      out.write("                <table class=\"table table-sm\">\r\n");
      out.write("                    <thead class=\"thead-dark\">\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th scope=\"col\"><input type=\"checkbox\"></th>\r\n");
      out.write("                        <th scope=\"col\">회원번호</th>\r\n");
      out.write("                        <th scope=\"col\">아이디</th>\r\n");
      out.write("                        <th scope=\"col\">이름</th>\r\n");
      out.write("                        <th scope=\"col\">생년월일</th>\r\n");
      out.write("                        <th scope=\"col\">성별</th>\r\n");
      out.write("                        <th scope=\"col\">전화번호</th>\r\n");
      out.write("                        <th scope=\"col\">주소</th>\r\n");
      out.write("                        <th scope=\"col\">가입일</th>\r\n");
      out.write("                        <th scope=\"col\">탈퇴여부</th>\r\n");
      out.write("                        <th scope=\"col\">블랙리스트여부</th>\r\n");
      out.write("                        <th scope=\"col\">회원등급</th>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th><input type=\"checkbox\"></th>\r\n");
      out.write("                        <th scope=\"row\">1</th>\r\n");
      out.write("                        <td>user02</td>\r\n");
      out.write("                        <td>유저이</td>\r\n");
      out.write("                        <td>2021.01.01</td>\r\n");
      out.write("                        <td>남</td>\r\n");
      out.write("                        <td>010-1234-5678</td>\r\n");
      out.write("                        <td>서울특별시 중구 남대문로 120 대일빌딩 2F, 3F</td>\r\n");
      out.write("                        <td>2021.01.10</td>\r\n");
      out.write("                        <td>N</td>\r\n");
      out.write("                        <td>Y</td>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th><input type=\"checkbox\"></th>\r\n");
      out.write("                        <th scope=\"row\">2</th>\r\n");
      out.write("                        <td>user03</td>\r\n");
      out.write("                        <td>유저삼</td>\r\n");
      out.write("                        <td>2021.01.01</td>\r\n");
      out.write("                        <td>남</td>\r\n");
      out.write("                        <td>010-1234-5678</td>\r\n");
      out.write("                        <td>서울특별시 중구 남대문로 120 대일빌딩 2F, 3F</td>\r\n");
      out.write("                        <td>2021.01.10</td>\r\n");
      out.write("                        <td>N</td>\r\n");
      out.write("                        <td>Y</td>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <th><input type=\"checkbox\"></th>\r\n");
      out.write("                        <th scope=\"row\">3</th>\r\n");
      out.write("                        <td>user04</td>\r\n");
      out.write("                        <td>유저사</td>\r\n");
      out.write("                        <td>2021.01.01</td>\r\n");
      out.write("                        <td>남</td>\r\n");
      out.write("                        <td>010-1234-5678</td>\r\n");
      out.write("                        <td>서울특별시 중구 남대문로 120 대일빌딩 2F, 3F</td>\r\n");
      out.write("                        <td>2021.01.10</td>\r\n");
      out.write("                        <td>N</td>\r\n");
      out.write("                        <td>Y</td>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                  </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"page_area\">\r\n");
      out.write("            <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                <ul class=\"pagination justify-content-center\">\r\n");
      out.write("                  <li class=\"page-item\">\r\n");
      out.write("                    <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                      <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                  <li class=\"page-item\">\r\n");
      out.write("                    <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                      <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"black_search\"><select id=\"black_search\" name=\"black_search\" required>\r\n");
      out.write("                <option selected>회원번호</option>\r\n");
      out.write("                <option>아이디</option>\r\n");
      out.write("                <option>이름</option>\r\n");
      out.write("                <option>탈퇴여부</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\"> <button type=\"button\" id=\"black_btn\">검색</button>\r\n");
      out.write("            <button type=\"button\" id=\"black_btn2\">삭제</button></div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"clear: both;\"></div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
